# Generated by Django 4.2.2 on 2023-12-28 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0003_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Tale',
        ),
    ]
