# Generated by Django 4.2.2 on 2023-12-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_rename_history_tale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tale',
        ),
    ]
