# Generated by Django 4.2.2 on 2023-12-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_delete_tale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
