# Generated by Django 4.2.2 on 2023-12-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_tale_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tale',
        ),
    ]
