# Generated by Django 4.2.2 on 2023-12-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_image_delete_tale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
