# Generated by Django 4.2.2 on 2023-12-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
